### ISSUE TITLE
[WingsManager] Add new wing

### ISSUE THREAD

**Issue by ApourtArtt** [ApourtArtt/NosTaleSDK#29]
ID: 5

**Comment by MarKYang5203** [comment]
if i used example code and succeed. 
so i can Create Item Item num 5 to see the added wing?

**Comment by ApourtArtt** [comment]
This is not related to your issue, I closed yours as everything I can tell you is described here: https://github.com/ApourtArtt/NostaleWidget/wiki/Wings-management

**Comment by MarKYang5203** [comment]
ok, thank sir .
last quest , modding can work on HK Server(chinese)?

**Comment by ApourtArtt** [comment]
Sorry, no clue but I doubt it will

**Comment by ApourtArtt** [comment]
Becomes a plugin on V2 - not SDK related anymore
