### ISSUE TITLE
it can support UTF-8?

### ISSUE THREAD

**Issue by MarKYang5203** [ApourtArtt/NosTaleSDK#41]
it can support UTF-8?  like chinese UTF-8 character.

**Comment by ApourtArtt** [comment]
Hello,

It handles ASCII and UTF-16

**Comment by MarKYang5203** [comment]
it can make handle chinese char?

**Comment by ApourtArtt** [comment]
UTF-16 handles chinese characters but I am not sure the client will handle them correctly

**Comment by ApourtArtt** [comment]
You can try to do something like this:
```cpp
TEWLabel* label = new TEWLabel(
		form,
		Border(45, 125, 110, 145),
		TextStyle(3, TextShadowOrientation::ShadowTopLeft, Bgra(0, 255, 255, 127), Bgra(255, 0, 0, 255), TextAlignment::CenteredCentered),
		TextPosition(0, 0, 66, 15, new WString(L"HERE"), true)
	);
```

And replace "HERE" by chinese characters (you might need to encode them if you hardcode them)

**Comment by MarKYang5203** [comment]
ok, but it can type chinese in chat ?

**Comment by ApourtArtt** [comment]
If you cannot without the SDK and don't do anything related to the chat with the SDK, no, if you do something with the SDK, I am not sure

**Comment by MarKYang5203** [comment]
ok thank a lot for reply~
