### ISSUE TITLE
Packet encryption

### ISSUE THREAD

**Issue by wings2004s** [ApourtArtt/NosTaleSDK#42]
Hi Iam trying to encrypt packets from client to server with xor encryption.
I made it working with login server but I cant decode not-authed packet (first) to a world server. I don't know why this happens.
![image](https://github.com/ApourtArtt/NosTaleSDK/assets/163059703/d89db2f0-ac64-49d2-967a-41d62f7884ce)
![image](https://github.com/ApourtArtt/NosTaleSDK/assets/163059703/a14ba641-7ecf-4007-a4aa-9832352d3ad5)

I use this code:
```
    .PacketConfig =
    {
        .EncryptFn = [](std::string Packet)
        {
            std::string newPacket = Packet;
            for (auto i = 0; i < newPacket.size(); i++)
                newPacket[i] = newPacket[i] ^ 0x50;

            return newPacket;
        },

...
void PacketManager::onSent(char* Packet)
{
	std::string packet(Packet);
	Logger::Log("Before encryption: %s", Packet);

	std::string encryptedPacket = config.EncryptFn(packet);
	
	memcpy(Packet, encryptedPacket.c_str(), encryptedPacket.size());

	std::string header = getPacketHeader(packet);

	sent.lock();

	Logger::Log("[SENT-ENCRYPTED] %s", Packet);

	if (sentSubscriptions.find(header) != sentSubscriptions.end())
	{
		for (auto& subscriber : sentSubscriptions[header])
			subscriber(packet);
	}

	sent.unlock();
}
```

What I do wrong?
thanks

**Comment by ApourtArtt** [comment]
Hey

This feature was not finished to implement and I did not test if it has effect when using it with subscription etc. I would advise to not use it and wait for the v2.
The reason why the first packet is not running through your encryption function is, the first packet is going through another route (the function I hook is before the game encryption, but the first packet is not encrypted, therefore another function should be hooked). It will be fixed on the v2 as the packet management will be changed (and will therefore be compatible with PhoenixBot for example)

**Comment by wings2004s** [comment]
thanks
